In [18]:
import pandas as pd

In [19]:
# netflix_titles
df1 = pd.read_csv('netflix_titles.csv')

print(df1)

     show_id     type                                    title  \
0         s1  TV Show                                       3%
1         s2    Movie                                     7:19
2         s3    Movie                                    23:59
3         s4    Movie                                        9
4         s5    Movie                                       21
...      ...      ...                                      ...
7782   s7783    Movie                                     Zozo
7783   s7784    Movie                                   Zubaan
7784   s7785    Movie                        Zulu Man in Japan
7785   s7786  TV Show                    Zumbo's Just Desserts
7786   s7787    Movie  ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS

               director                                               cast  \
0                   NaN  João Miguel, Bianca Comparato, Michel Gomes, R...
1     Jorge Michel Grau  Demián Bichir, Héctor Bonilla, Oscar Serrano, ...
2          Gilbert Chan  Tedd Chan, Stella Chung, Henley Hii, Lawrence ...
3           Shane Acker  Elijah Wood, John C. Reilly, Jennifer Connelly...
4        Robert Luketic  Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...
...                 ...                                                ...
7782        Josef Fares  Imad Creidi, Antoinette Turk, Elias Gergi, Car...
7783        Mozez Singh  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...
7784                NaN                                            Nasty C
7785                NaN                         Adriano Zumbo, Rachel Khoo
7786           Sam Dunn                                                NaN

                                                country          date_added  \
0                                                Brazil     August 14, 2020
1                                                Mexico   December 23, 2016
2                                             Singapore   December 20, 2018
3                                         United States   November 16, 2017
4                                         United States     January 1, 2020
...                                                 ...                 ...
7782  Sweden, Czech Republic, United Kingdom, Denmar...    October 19, 2020
7783                                              India       March 2, 2019
7784                                                NaN  September 25, 2020
7785                                          Australia    October 31, 2020
7786              United Kingdom, Canada, United States       March 1, 2020

      release_year rating   duration  \
0             2020  TV-MA  4 Seasons
1             2016  TV-MA     93 min
2             2011      R     78 min
3             2009  PG-13     80 min
4             2008  PG-13    123 min
...            ...    ...        ...
7782          2005  TV-MA     99 min
7783          2015  TV-14    111 min
7784          2019  TV-MA     44 min
7785          2019  TV-PG   1 Season
7786          2019  TV-MA     90 min

                                              listed_in  \
0     International TV Shows, TV Dramas, TV Sci-Fi &...
1                          Dramas, International Movies
2                   Horror Movies, International Movies
3     Action & Adventure, Independent Movies, Sci-Fi...
4                                                Dramas
...                                                 ...
7782                       Dramas, International Movies
7783     Dramas, International Movies, Music & Musicals
7784  Documentaries, International Movies, Music & M...
7785                 International TV Shows, Reality TV
7786                    Documentaries, Music & Musicals

                                            description
0     In a future where the elite inhabit an island ...
1     After a devastating earthquake hits Mexico Cit...
2     When an army recruit is found dead, his fellow...
3     In a postapocalyptic world, rag-doll robots hi...
4     A brilliant group of students become card-coun...
...                                                 ...
7782  When Lebanon's Civil War deprives Zozo of his ...
7783  A scrappy but poor boy worms his way into a ty...
7784  In this documentary, South African rapper Nast...
7785  Dessert wizard Adriano Zumbo looks for the nex...
7786  This documentary delves into the mystique behi...

[7787 rows x 12 columns]

In [20]:
# netflix_titles_2
df2 = pd.read_csv('netflix_titles_2.csv')

print(df2)

       show_id     type                                        title  \
0     81145628    Movie      Norm of the North: King Sized Adventure
1     80117401    Movie                   Jandino: Whatever it Takes
2     70234439  TV Show                           Transformers Prime
3     80058654  TV Show             Transformers: Robots in Disguise
4     80125979    Movie                                 #realityhigh
...        ...      ...                                          ...
6229  80000063  TV Show                                 Red vs. Blue
6230  70286564  TV Show                                        Maron
6231  80116008    Movie       Little Baby Bum: Nursery Rhyme Friends
6232  70281022  TV Show  A Young Doctor's Notebook and Other Stories
6233  70153404  TV Show                                      Friends

                      director  \
0     Richard Finn, Tim Maltby
1                          NaN
2                          NaN
3                          NaN
4             Fernando Lebrija
...                        ...
6229                       NaN
6230                       NaN
6231                       NaN
6232                       NaN
6233                       NaN

                                                   cast  \
0     Alan Marriott, Andrew Toth, Brian Dobson, Cole...
1                                      Jandino Asporaat
2     Peter Cullen, Sumalee Montano, Frank Welker, J...
3     Will Friedle, Darren Criss, Constance Zimmer, ...
4     Nesta Cooper, Kate Walsh, John Michael Higgins...
...                                                 ...
6229  Burnie Burns, Jason Saldaña, Gustavo Sorola, G...
6230  Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...
6231                                                NaN
6232  Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...
6233  Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...

                                       country         date_added  \
0     United States, India, South Korea, China  September 9, 2019
1                               United Kingdom  September 9, 2016
2                                United States  September 8, 2018
3                                United States  September 8, 2018
4                                United States  September 8, 2017
...                                        ...                ...
6229                             United States                NaN
6230                             United States                NaN
6231                                       NaN                NaN
6232                            United Kingdom                NaN
6233                             United States                NaN

      release_year    rating    duration  \
0             2019     TV-PG      90 min
1             2016     TV-MA      94 min
2             2013  TV-Y7-FV    1 Season
3             2016     TV-Y7    1 Season
4             2017     TV-14      99 min
...            ...       ...         ...
6229          2015        NR  13 Seasons
6230          2016     TV-MA   4 Seasons
6231          2016       NaN      60 min
6232          2013     TV-MA   2 Seasons
6233          2003     TV-14  10 Seasons

                                              listed_in  \
0                    Children & Family Movies, Comedies
1                                       Stand-Up Comedy
2                                              Kids' TV
3                                              Kids' TV
4                                              Comedies
...                                                 ...
6229  TV Action & Adventure, TV Comedies, TV Sci-Fi ...
6230                                        TV Comedies
6231                                             Movies
6232           British TV Shows, TV Comedies, TV Dramas
6233                     Classic & Cult TV, TV Comedies

                                            description
0     Before planning an awesome wedding for his gra...
1     Jandino Asporaat riffs on the challenges of ra...
2     With the help of three human allies, the Autob...
3     When a prison ship crash unleashes hundreds of...
4     When nerdy high schooler Dani finally attracts...
...                                                 ...
6229  This parody of first-person shooter games, mil...
6230  Marc Maron stars as Marc Maron, who interviews...
6231  Nursery rhymes and original music for children...
6232  Set during the Russian Revolution, this comic ...
6233  This hit sitcom follows the merry misadventure...

[6234 rows x 12 columns]

In [21]:
# as we want to figure out what characteristic may influence the popularity, show_id and title are meaningless, so drop them to simplify
df1 = df1.drop(columns = ['show_id', 'title'])
df2 = df2.drop(columns = ['show_id', 'title'])

In [22]:
frames = [df1, df2]
raw_result = pd.concat(frames)
result = pd.concat(frames).drop_duplicates()

print(raw_result)
print(result)

         type           director  \
0     TV Show                NaN
1       Movie  Jorge Michel Grau
2       Movie       Gilbert Chan
3       Movie        Shane Acker
4       Movie     Robert Luketic
...       ...                ...
6229  TV Show                NaN
6230  TV Show                NaN
6231    Movie                NaN
6232  TV Show                NaN
6233  TV Show                NaN

                                                   cast         country  \
0     João Miguel, Bianca Comparato, Michel Gomes, R...          Brazil
1     Demián Bichir, Héctor Bonilla, Oscar Serrano, ...          Mexico
2     Tedd Chan, Stella Chung, Henley Hii, Lawrence ...       Singapore
3     Elijah Wood, John C. Reilly, Jennifer Connelly...   United States
4     Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...   United States
...                                                 ...             ...
6229  Burnie Burns, Jason Saldaña, Gustavo Sorola, G...   United States
6230  Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...   United States
6231                                                NaN             NaN
6232  Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...  United Kingdom
6233  Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...   United States

             date_added  release_year rating    duration  \
0       August 14, 2020          2020  TV-MA   4 Seasons
1     December 23, 2016          2016  TV-MA      93 min
2     December 20, 2018          2011      R      78 min
3     November 16, 2017          2009  PG-13      80 min
4       January 1, 2020          2008  PG-13     123 min
...                 ...           ...    ...         ...
6229                NaN          2015     NR  13 Seasons
6230                NaN          2016  TV-MA   4 Seasons
6231                NaN          2016    NaN      60 min
6232                NaN          2013  TV-MA   2 Seasons
6233                NaN          2003  TV-14  10 Seasons

                                              listed_in  \
0     International TV Shows, TV Dramas, TV Sci-Fi &...
1                          Dramas, International Movies
2                   Horror Movies, International Movies
3     Action & Adventure, Independent Movies, Sci-Fi...
4                                                Dramas
...                                                 ...
6229  TV Action & Adventure, TV Comedies, TV Sci-Fi ...
6230                                        TV Comedies
6231                                             Movies
6232           British TV Shows, TV Comedies, TV Dramas
6233                     Classic & Cult TV, TV Comedies

                                            description
0     In a future where the elite inhabit an island ...
1     After a devastating earthquake hits Mexico Cit...
2     When an army recruit is found dead, his fellow...
3     In a postapocalyptic world, rag-doll robots hi...
4     A brilliant group of students become card-coun...
...                                                 ...
6229  This parody of first-person shooter games, mil...
6230  Marc Maron stars as Marc Maron, who interviews...
6231  Nursery rhymes and original music for children...
6232  Set during the Russian Revolution, this comic ...
6233  This hit sitcom follows the merry misadventure...

[14021 rows x 10 columns]
         type           director  \
0     TV Show                NaN
1       Movie  Jorge Michel Grau
2       Movie       Gilbert Chan
3       Movie        Shane Acker
4       Movie     Robert Luketic
...       ...                ...
6219  TV Show                NaN
6220  TV Show                NaN
6221  TV Show                NaN
6222  TV Show                NaN
6231    Movie                NaN

                                                   cast        country  \
0     João Miguel, Bianca Comparato, Michel Gomes, R...         Brazil
1     Demián Bichir, Héctor Bonilla, Oscar Serrano, ...         Mexico
2     Tedd Chan, Stella Chung, Henley Hii, Lawrence ...      Singapore
3     Elijah Wood, John C. Reilly, Jennifer Connelly...  United States
4     Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...  United States
...                                                 ...            ...
6219  Sarah Natochenny, Laurie Hymes, Jessica Paquet...          Japan
6220            Gage Munroe, Scott McCord, Jenna Warren         Canada
6221  You, Reina Triendl, Ryota Yamasato, Yoshimi To...          Japan
6222  Mary-Louise Parker, Hunter Parrish, Alexander ...  United States
6231                                                NaN            NaN

             date_added  release_year    rating   duration  \
0       August 14, 2020          2020     TV-MA  4 Seasons
1     December 23, 2016          2016     TV-MA     93 min
2     December 20, 2018          2011         R     78 min
3     November 16, 2017          2009     PG-13     80 min
4       January 1, 2020          2008     PG-13    123 min
...                 ...           ...       ...        ...
6219      April 1, 2019          2019  TV-Y7-FV  2 Seasons
6220      April 1, 2016          2012      TV-Y  2 Seasons
6221      April 1, 2016          2016     TV-14  2 Seasons
6222      April 1, 2014          2012     TV-MA  8 Seasons
6231                NaN          2016       NaN     60 min

                                              listed_in  \
0     International TV Shows, TV Dramas, TV Sci-Fi &...
1                          Dramas, International Movies
2                   Horror Movies, International Movies
3     Action & Adventure, Independent Movies, Sci-Fi...
4                                                Dramas
...                                                 ...
6219                             Anime Series, Kids' TV
6220                                           Kids' TV
6221                 International TV Shows, Reality TV
6222                             TV Comedies, TV Dramas
6231                                             Movies

                                            description
0     In a future where the elite inhabit an island ...
1     After a devastating earthquake hits Mexico Cit...
2     When an army recruit is found dead, his fellow...
3     In a postapocalyptic world, rag-doll robots hi...
4     A brilliant group of students become card-coun...
...                                                 ...
6219  Ash and his Pikachu travel to the Alola region...
6220  In Justin's dreams, he and his imaginary frien...
6221  A new set of six men and women start their liv...
6222  A suburban mother starts selling marijuana to ...
6231  Nursery rhymes and original music for children...

[9553 rows x 10 columns]